django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http.response import HttpResponse


#only me
def homeFunc(request):
  return HttpResponse('<h6>HOME</h6>')


urlpatterns = [
    path('', homeFunc),
    path('admin/', admin.site.urls),
    # we declare only student/...edit...add.....
    path('student/', include('student.urls')),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'  #necessary for navigation

urlpatterns = [  # name is used in href =
    path('', views.all_students, name='allStudents'),  #name= for navigation
    path('add/', views.add_student, name='addStudent'),
    path('edit/', views.edit_student, name='editStudent')
]

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render
#from django.http.response import HttpResponse
# Create your views here.


def all_students(request):
  myVars = {
      'fname': 'Akram',
      'lname': 'Boutoutaou',
      'mylist': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      'mydict': {
          'python': 'django'
      },
      'smallWord': 'hello small world',
      'myEmptylist': []
  }  #context passes dictionary
  return render(request, 'student.html', context=myVars)


def add_student(request):

  return render(request, 'add.html')


def edit_student(request):
  return render(request, 'edit.html')

student/templates/add.html
<!-- name of folder must be 'templates'
  to recognize it as a template folder -->

{%extends 'base.html'%} <!--like the head-->
{% load static %} <!--
like import static and we can put in one time on base.html but we don't for secure our website 
-->

{% block content %}
<h1>template add student</h1>

<a href="{% url 'student:allStudents' %}"> <!--NavigateTo ps : it works on autonomous url not on replit mini browser-->
  All Student 
</a>
<br>
<img src="{%static 'paris.jpg'%}">
{#didn't work #}

{% endblock%}

student/templates/edit.html
<!-- name of folder must be 'templates'
  to recognize it as a template folder -->

{%extends 'base.html'%}

{% block content %}
<h1>template edit student</h1>

<a href="{% url 'student:allStudents' %}">
  All Student 
</a>
{% endblock%}

student/templates/student.html
<!-- name of folder must be 'templates'
  to recognize it as a template folder -->

{%extends 'base.html'%}

{% block content %}

<h1>template HOME all students</h1>
<h1>first name is : {{fname}}</h1>
<h1>last  name is : {{lname}}</h1>

<a href="{% url 'student:addStudent' %}">
  Add Student 
</a>
<br>
<a href="{% url 'student:editStudent' %}">
  Edit Student 
</a>
<br>

{#this is comment like <!--zefezf-->#}

{{fname}} <!-- key of context=myVars-->
<br>
{{lname}}
<br>
{{mylist}}
<br>
{{mydict}}
<br>

{{smallWord | upper}} <!-- filter python function-->
<br>
{{fname | length}} <!-- filter python function-->
<br>
{{lname | capfirst}} <!-- filter python function-->
<br>
{{fname | lower | capfirst }} 
<br>

{% for item in mylist%} 
{{item}} 
<br>
{%endfor%}
<br>

<ul>
  {% for item in mylist%}
  <li>
      {{item}}
  </li>
  {%endfor%}
</ul>
<br>
<ul>
  {% for item in mydict %}
  <li>
      {{item}}
  </li>
  {%endfor%}
</ul>
<br>
<ul>
  {% for item in myEmptylist%}
  <li>{{item}}</li>
  {%empty%} <!-- if list=[] and also run if we don't even                 declare the variable myEmptylist -->
  <li>there is no in this list</li>
  {%endfor%}
</ul>
<br>
{%if fname == 'Akram'%}
{{fname}}
{%endif%}
<br>
{%if fname == 'ramy'%}
<h2>{welcome {fname}}</h2>
{%else%}
<h2>ur not akram : ur {{lname}} </h2>
{%endif%}
<br>
{% endblock%}

templates/base.html
<!--
we have to declare on project setting :
TEMPLATES = [
{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR,'templates/')],
-->
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>
  
  <h1>this is base block</h1>
  
  {% block content %}
  
  {% endblock%}

  <h1>this is end block</h1>
</body>
</html> 